Fix vllm config not set with lora merge
```log
Traceback (most recent call last):
File "vllm/v1/executor/multiproc_executor.py", line 966, in worker_busy_loop
  output = func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
File "verl/workers/rollout/vllm_rollout/utils.py", line 405, in update_weights_from_ipc
  process_weights_after_loading(model, model_config, self.device)
File "vllm/model_executor/model_loader/utils.py", line 107, in process_weights_after_loading
  quant_method.process_weights_after_loading(module)
File "vllm/model_executor/layers/fused_moe/unquantized_fused_moe_method.py", line 238, in process_weights_after_loading
  self._setup_kernel(
File "vllm/model_executor/layers/fused_moe/unquantized_fused_moe_method.py", line 170, in _setup_kernel
  self.moe_kernel = make_unquantized_moe_kernel(
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "vllm/model_executor/layers/fused_moe/oracle/unquantized.py", line 366, in make_unquantized_moe_kernel
  experts = experts_cls(
            ^^^^^^^^^^^^
File "vllm/model_executor/layers/fused_moe/flashinfer_cutlass_moe.py", line 98, in __init__
  get_current_vllm_config().compilation_config.max_cudagraph_capture_size
  ^^^^^^^^^^^^^^^^^^^^^^^^^
File "vllm/config/vllm.py", line 1946, in get_current_vllm_config
  raise AssertionError(
AssertionError: Current vLLM config is not set. This typically means get_current_vllm_config() was called outside of a set_current_vllm_config() context, or a CustomOp was instantiated at module import time or model forward time when config is not set. For tests that directly test custom ops/modules, use the 'default_vllm_config' pytest fixture from tests/conftest.py.
```

Signed-off-by: Hollow Man <hollowman@opensuse.org>